version: '3.0'
services: 
    mariadb:
        image: mariadb:10.4.5
        container_name: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: passme
            MYSQL_DATABASE: WhatsAppDB
            MYSQL_USER: user
            MYSQL_PASSWORD: passme
        ports:
            - 3306:3306
        volumes:
            -  ${PWD}/mariadb:/var/lib/mysql
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mariadb:db
        ports:
            - 8000:80
        environment:
            MYSQL_ROOT_PASSWORD: passme
    nginx:
        build: ./WhatsAppClient
        ports: 
            - 80:80
    server:
        build: ./Server
        ports: 
            - 8080:8000
