version: '3.0'
services: 
    db:
        image: mysql:5.7
        volumes:
        - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: passme
            MYSQL_DATABASE: WhatsAppDB
            MYSQL_USER: user
            MYSQL_PASSWORD: passme
    phpmyadmin:
        depends_on:
        - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
        - '8000:80'
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: password
    nginx:
        build: ./WhatsAppClient
        ports: 
            - 80:80
    server:
        build: ./Server
        ports: 
            - 2000:2000
    websocket:
        build: ./websocket
        ports: 
            - 2000:2000
volumes:
    db_data: