version: '3.0'
services: 
    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        ports: 
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: passme
            MYSQL_DATABASE: WhatsAppDB
            MYSQL_USER: user
            MYSQL_PASSWORD: passme
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: password
    nginx:
        build: ./WhatsAppClient
        ports: 
            - 80:80
    server:
        depends_on:
            - db
        build: ./Server
        ports: 
            - 2000:2000
        links: 
            - db
    websocket:
        build: ./websocket
        ports: 
            - 8000:8000
        links:
            - server


volumes:
    db_data: